version: '3'

services:
  nginx:
    image: openresty:1.13.6.2-debian
    container_name: openresty
    restart: always
    ports:
      - 80:80
      - 8080:80
      - 8081:80
      - 443:443
    volumes:
      - ./nginx.conf /etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - /data/logs/nginx:/var/log/nginx
      - /data/web:/data/web
